track_package:
  name: Track Package
  description: Track a new package
  fields:
    tracking_id:
      name: Tracking ID
      description: The tracking ID of the package
      example: "ABC123456789"
      required: true
      selector:
        text:
    name:
      name: Sensor Name
      description: Optional name for the sensor (default is 'Parcel <TrackingID>')
      example: "My Amazon Package"
      required: false
      selector:
        text:
    zipcode:
      name: Zip Code
      description: Optional zip/postal code for more accurate tracking
      example: "12345"
      required: false
      selector:
        text:

remove_package:
  name: Remove Package
  description: Remove a tracked package
  fields:
    tracking_id:
      name: Tracking ID
      description: The tracking ID of the package to remove
      example: "ABC123456789"
      required: true
      selector:
        text:
